server:
  port: 7000
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: eureka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      # 不自动创建表
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      # 关闭jpa懒加载
    open-in-view: false
  datasource:
    url: jdbc:mysql://192.168.129.133:3306/guanggao?autoReconnect=true
    username: root
    password: 123456
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/


